# Generated by Django 5.1.4 on 2025-01-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_partida', models.CharField(max_length=255, verbose_name='Dirección de partida')),
                ('direccion_llegada', models.CharField(max_length=255, verbose_name='Dirección de llegada')),
                ('peso', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Peso (kg)')),
                ('largo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Largo (cm)')),
                ('ancho', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ancho (cm)')),
                ('alto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Alto (cm)')),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distancia (km)')),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo estimado ($)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
    ]
